---
- name: Copy CA cert to hosts
  copy:
    src: cert/CA.pem
    dest: /etc/vault/certs/CA.pem
    owner: vault
    group: vault
    mode: 0660 
  tags: blabla 
  
- name: Copy CA cert to hosts
  copy:
    src: cert/rootCA.pem
    dest: /etc/vault/certs/rootCA.pem
    owner: vault
    group: vault
    mode: 0660 
  tags: blabla   
    
- name: Copy vault key to hosts
  copy:
    src: cert/consul.key
    dest: /etc/vault/certs/vault.key
    owner: vault
    group: vault
    mode: 0660
    
- name: Copy vault cert to hosts
  copy:
    src: cert/consul.pem
    dest: /etc/vault/certs/vault.pem
    owner: vault
    group: vault
    mode: 0660    
    
- name: Copy vault_server.hcl - now with ssl config
  template:
    src: vault_server.hcl.j2
    dest: /etc/vault/vault_server.hcl
    owner: vault
    group: vault
    mode: 0660
  tags: ssl_vault_consul  
  
- name: Create folder for certs
  file:
    path: /usr/local/etc/consul/certs/
    state: directory  
    owner: consul
    group: consul  
  
- name: Copy CA cert to hosts
  copy:
    src: cert/CA.pem
    dest: /usr/local/etc/consul/certs/CA.pem
    owner: consul
    group: consul
    mode: 0660   
    
- name: Copy consul key to hosts
  copy:
    src: cert/consul.key
    dest: /usr/local/etc/consul/certs/consul.key
    owner: consul
    group: consul
    mode: 0660
    
- name: Copy consul cert to hosts
  copy:
    src: cert/consul.pem
    dest: /usr/local/etc/consul/certs/consul.pem
    owner: consul
    group: consul
    mode: 0660             
  
- name: Copy client_agent.json.j2 - now with ssl config
  template:
    src: client_agent.json.j2
    dest: /usr/local/etc/consul/client_agent.json
    owner: consul
    group: consul
    mode: 0660
  
- name: Enable consul service and start
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes    
    name: consul
    
- name: Enable vault service and start
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes    
    name: vault    
    
    
    
