- name: enable and start firewalld
  service: 
    name: firewalld 
    enabled: yes
    state: started
  tags:
    - firewall 

- name: set port policy
  firewalld: 
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - "{{ kafka_plain_port }}"
    - "{{ zookeeper_client_port }}"
    - "{{ zookeeper_leader_port }}"
    - "{{ zookeeper_election_port }}"
  tags:
    - firewall 
  notify: firewall restart
